### ISSUE TITLE
user.css not working with Ferdi

### ISSUE THREAD

**Issue by obvionaoe** [vednoc/dark-instagram#1]
The theme is quite broken for Ferdi, I'm not sure if it is because of Ferdi itself, or if Instagram updated something

**Comment by vednoc** [comment]
Ah, I'm afraid there isn't much I can do in this particular case. Ferdi is known to inject the CSS in the `<head>` element, and Stylus does it at the very end of the `<body>` element. This matters when it comes to [specificity][0], the latter always wins, and very often the use of `!important` isn't necessary.

Can you try replacing default `:root` with `:root:not(#z)` to see if it changes anything? If not, try adding another `:not(#x)` to see if you're able to win on specificity. If this works, I'll add it in the next update.


[0]: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by obvionaoe** [comment]
Replacing `:root` with `:root:not(#z)` fixed it! btw I might as well mention it, I currently maintain [obvionaoe/dark](https://github.com/obvionaoe/dark) where I keep some dark themes for a few messaging service for Ferdi/Franz/Rambox and your themes have helped me a lot! Thank you so much!

**Comment by vednoc** [comment]
I'm happy to hear that it works! Thanks for using my themes. :heart:

P.S. Would you like me to add a link to your project in credits?

**Comment by obvionaoe** [comment]
If it isn't too much of hassle, I'd appreciate it! :blush:
