### ISSUE TITLE
Broken colors in new update

### ISSUE THREAD

**Issue by remaindeer** [vednoc/dark-instagram#7]
Hi, recent changes to Instagram has broken the formatting of this style. Could you take a look at it?

![image](https://user-images.githubusercontent.com/402154/171270797-23697e36-7eb2-44d6-899a-600bfc6a10f9.png)

**Comment by marrrc** [comment]
It seems like Instagram introduced a set of new variables. Didn't have much time, also could not quite recall how dark-instagram colors were used previously, since the old var names are quite arbitrary, so I won't provide a PR. But for now, you can mostly fix it yourself by adding the following after ```/// Instagram variables```:

```
        --ig-badge: 237,73,86;
        --ig-close-friends-refreshed: 28,209,79;
        --ig-elevated-background: var(--darken-rgb);    /// Elevated background color.
        --ig-elevated-separator: var(--darker-rgb);     /// Elevated border colors.
        --ig-error-or-destructive: 237,73,86;
        --ig-facebook-blue: 53,121,234;
        --ig-focus-stroke: 168,168,168;
        --ig-full-screen-background: 54,54,54;
        --ig-highlight-background: var(--darker-rgb);   /// Highlight background color.
        --ig-link: var(--accent-rgb);                   /// Links.
        --ig-live-badge: 255,1,105;
        --ig-primary-background:  var(--darken-rgb);    /// Primary background color.
        --ig-primary-button: var(--accent-rgb);         /// Links.
        --ig-primary-text: var(--light-rgb);            /// Main text color.
        --ig-secondary-background:  var(--dark-rgb);    /// Secondary background color.
        --ig-secondary-button: var(--accent-rgb);       /// Links.
        --ig-secondary-text: var(--lighter-rgb);        /// Secondary text.
        --ig-separator: var(--darker-rgb);              /// Global border colors.
        --post-separator: var(--darker-rgb);            /// Post border color.
        --ig-stroke: var(--darker-rgb);                 /// Stroke colors.
        --ig-subscribers-only: 118,56,250;
        --ig-success: 88,195,34;
        --ig-temporary-highlight: var(--darken-rgb);
        --ig-tertiary-text: var(--lighter-rgb);         /// Tertiary text.
        --ig-text-on-color: var(--dark-rgb);            /// Text on color.
        --ig-text-on-media: var(--dark-rgb);            /// Text on media.
```

I did not replace every new value, only the meaningful ones that make everything go dark. Again, this may differ from the last version, but it works for me. :)

**Comment by remaindeer** [comment]
Thanks! Btw, do you know if @vednoc is no longer working on this project?

**Comment by marrrc** [comment]
sadly no idea, only stumbled upon this repo a couple of weeks ago myself :)

**Comment by vednoc** [comment]
Pretty much all my userstyles are on a hiatus. I'll try to release a new update in a couple of hours. Thank you, @marrrc, for looking into it! If you or anyone else would like to contribute, please don't hesitate to get in touch with me.
